services:
  - type: web
    name: agentraxsync
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: SCALEKIT_ENVIRONMENT_URL
        sync: false
      - key: SCALEKIT_CLIENT_ID
        sync: false
      - key: SCALEKIT_CLIENT_SECRET
        sync: false
